package main

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

// Address doc
// FIXME whatever
type Address struct {
	//Country doc
	// TODO should be filtered out
	Country string `json:"country,omitempty"`
	// TODO should be filtered out
	//PostCode doc
	PostCode int `json:"postcode,omitempty"`
}

// Person doc
// TODO should be filtered out
// with multiline
type Person struct {
	//FirstName doc
	FirstName string `json:"firstName,omitempty"`
	//LastName doc
	//FIXME whatever
	LastName string `json:",omitempty"`
	//MiddleName doc
	MiddleName string `json:"middleName"`

	//Field without tag and
	// multiline comment and something to escape \ "
	// ---
	// If we encounter a --- we skip everything after that separator
	HeightInPounds int
}

type UndocumentedStruct struct {
	UndocumentedField string
}

type StructWithEmbeddedStruct struct {
	Person
	Address
}

// This only has a struct documentation
type StructWithStructDocOnly struct {
	Person
	Address
}

type StructWithFieldDocOnly struct {
	//MiddleName doc
	MiddleName string `json:"middleName"`
}

// StructWithAllFilters doc
// +optional
// +nullable
// +enum=["a","b"]
// +listType=map
// +listMapKey=name
// +patchMergeKey=name
// +patchStrategy=merge
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:validation:Required
// +genclient:noVerbs
type StructWithAllFilters struct {
	// Field doc
	// +kubebuilder:validation:MinLength=1
	// +optional
	Name string `json:"name"`
}

var expected = strings.TrimSpace(`
// Code generated by swagger-doc. DO NOT EDIT.

package main

func (Address) SwaggerDoc() map[string]string {
	return map[string]string{
		"":         "Address doc",
		"country":  "Country doc",
		"postcode": "PostCode doc",
	}
}

func (Person) SwaggerDoc() map[string]string {
	return map[string]string{
		"":               "Person doc\nwith multiline",
		"firstName":      "FirstName doc",
		"LastName":       "LastName doc",
		"middleName":     "MiddleName doc",
		"HeightInPounds": "Field without tag and\nmultiline comment and something to escape \\ \"",
	}
}

func (UndocumentedStruct) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (StructWithEmbeddedStruct) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (StructWithStructDocOnly) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "This only has a struct documentation",
	}
}

func (StructWithFieldDocOnly) SwaggerDoc() map[string]string {
	return map[string]string{
		"middleName": "MiddleName doc",
	}
}

func (StructWithAllFilters) SwaggerDoc() map[string]string {
	return map[string]string{
		"":     "StructWithAllFilters doc",
		"name": "Field doc",
	}
}`)

func TestSwaggerDocGeneration(t *testing.T) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "description_generator_test.go", nil, parser.ParseComments)
	if err != nil {
		panic(err)
	}
	c := Parse(f)

	buf := ""
	for line := range c {
		buf = buf + line + "\n"
	}
	buf = strings.TrimSpace(buf)
	if buf != expected {
		t.Fatalf("Expected: %s, got: %s", expected, buf)
	}
}

func TestShouldFilter(t *testing.T) {
	for _, tc := range []struct {
		line     string
		expected bool
	}{
		{"TODO refactor this", true},
		{"FIXME broken", true},
		{"+optional", true},
		{"+nullable", true},
		{"+enum=[\"a\",\"b\"]", true},
		{"+listType=map", true},
		{"+listMapKey=name", true},
		{"+patchMergeKey=name", true},
		{"+patchStrategy=merge", true},
		{"+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object", true},
		{"+kubebuilder:validation:Required", true},
		{"+genclient:noVerbs", true},
		{"This is a normal doc comment", false},
		{"Returns the name of the resource", false},
		{"", false},
	} {
		t.Run(tc.line, func(t *testing.T) {
			if got := shouldFilter(tc.line); got != tc.expected {
				t.Errorf("shouldFilter(%q) = %v, want %v", tc.line, got, tc.expected)
			}
		})
	}
}
